#!/usr/local/bin/node --use_strict
"use strict";

const child_process = require('child_process');
const fs = require('fs');
const readline = require('readline');

const Decomposition = require('../lib/decomposition');

const kDelimiter = 'BREAK';
const kDirectory = 'cordova-build-override/www/assets/characters';

const augmentRows = (all, rows) => {
  for (let character of all) {
    const row = rows[character];
    row.dependencies = {};
    Array.from(row.decomposition).map((x) => {
      if (Decomposition.ids_data[x] || x === '？') return;
      const data = rows[x];
      if (!data) throw new Error(`Missing component of ${character}: ${x}\n` +
                                 JSON.stringify(row));
      let value = data.definition || '(unknown)';
      if (data.pinyin.length > 0) {
        value = data.pinyin.join(', ') + ' - ' + value;
      }
      row.dependencies[x] = value;
    });
    row.components = row.strokes.map(
        (x, i) => computeComponents(character, i, rows));
  }
}

const computeComponents = (character, index, rows, result) => {
  result = result || {};
  result[character] = index;
  const data = rows[character];
  if (!data) throw new Error(`Computing component for ${character}.`);
  const match = data.matches[index];
  if (!data.matches[index]) return result;

  // Walk the path down the decomposition tree to find the component.
  let node = Decomposition.convertDecompositionToTree(data.decomposition);
  for (let i of data.matches[index]) {
    if (!node.children) {
      node = null;
      break;
    }
    node = node.children[i];
  }
  if (!node || node.type !== 'character' || !rows[node.value]) {
    throw new Error(`Error matching component for ${character}, ${index}:\n` +
                    `Final node: ${JSON.stringify(node)}\n` +
                    JSON.stringify(data));
  }

  // Determine what index we are into that component.
  let child_index = 0;
  for (let i = 0; i < index; i++) {
    if (JSON.stringify(data.matches[i]) === JSON.stringify(match)) {
      child_index += 1;
    }
  }
  return computeComponents(node.value, child_index, rows, result);
}

const dumpCharacters = (all, rows) => {
  for (let character of all) {
    const row = rows[character];
    const filename = `${kDirectory}/${character.charCodeAt(0)}`;
    fs.writeFileSync(filename, JSON.stringify(rows[character]));
  }
  fs.writeFileSync(`${kDirectory}/all.txt`, all.join(''));
}

const parseLine = (line, delimiter) => {
  const pieces = line.trim().split(delimiter)
  if (pieces.length !== 2) throw new Error(line);
  const row = JSON.parse(pieces[0]);
  const row2 = JSON.parse(pieces[1]);
  if (!row.character) throw new Error(line);
  if (row.character !== row2.character) throw new Error(line);
  for (let key in row2) {
    row[key] = row2[key];
  }
  delete row.normalized_medians;
  return row;
}

const main = () => {
  // TODO(skishore): This whole function is a terrible hack! Clean it up.

  // Combine each line of the dictionary.txt and graphics.txt files.
  const spacers = [];
  Array.from(kDelimiter).slice(1).map((x) => spacers.push('/dev/null'));
  const spacer = spacers.join(' ');
  console.log('Preparing...');
  child_process.execSync(
      `paste -d ${kDelimiter} ../makemeahanzi/dictionary.txt ` +
      `${spacer} ../makemeahanzi/graphics.txt > makemeahanzi.txt`);

  // Read in the combined-file line-by-line into memory.
  console.log('Reading...');
  const input = fs.createReadStream('makemeahanzi.txt');
  const reader = readline.createInterface({input: input});
  const rows = {};
  const all = [];
  reader.on('line', (line) => {
    const row = parseLine(line, kDelimiter);
    rows[row.character] = row;
    all.push(row.character);
  });

  // Dump each part into a characters/part-xxx file, then compress them all.
  reader.on('close', () => {
    console.log('Augmenting...');
    augmentRows(all, rows);
    console.log('Dumping...');
    dumpCharacters(all, rows);
    console.log('Cleaning up...');
    child_process.execSync('rm makemeahanzi.txt', () => 0);
    console.log('Done!');
  });
}

main();
