#!/bin/bash

DIRECTORY="/Users/skishore/Dropbox/Projects/inkstone"
ZIPALIGN="/Users/skishore/Library/Android/sdk/build-tools/23.0.1/zipalign"

# Clear the build directory.
rm -r .build
meteor remove-platform android
meteor add-platform android

# Run the Meteor build script. Since Meteor copies the cordova-build-override
# directory, we manually exclude the saved character data files in our build.
mv cordova-build-override/www/assets/characters .characters
meteor build .build --server localhost:3785
cp -R cordova-build-override/* .build/android/project/assets/.
mv .characters cordova-build-override/www/assets/characters

# Run the Cordova build script.
pushd .build/android/project/cordova
./build --release
cd ../build/outputs/apk

# Sign the output. Will prompt for passwords.
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.keystore project-armv7-release-unsigned.apk inkstone
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.keystore project-x86-release-unsigned.apk inkstone
$ZIPALIGN -c -f 4 project-armv7-release-unsigned.apk project-armv7-release.apk
$ZIPALIGN -c -f 4 project-x86-release-unsigned.apk project-x86-release.apk

# Copy the output to a staging location in Dropbox.
cp project-armv7-release.apk $DIRECTORY/inkstone-armv7.new.apk
cp project-x86-release.apk $DIRECTORY/inkstone-x86.new.apk
popd
