#!/bin/bash

DIRECTORY="~/Dropbox/Projects/inkstone"

# Move the staging build to the release build in Dropbox.
mv $DIRECTORY/inkstone-armv7.apk $DIRECTORY/inkstone-armv7.bak.apk
mv $DIRECTORY/inkstone-x86.apk $DIRECTORY/inkstone-x86.bak.apk
mv $DIRECTORY/inkstone-armv7.new.apk $DIRECTORY/inkstone-armv7.apk
mv $DIRECTORY/inkstone-x86.new.apk $DIRECTORY/inkstone-x86.apk
