#!/bin/bash

# Move the staging build to the release build in Dropbox.
mv ~/Dropbox/Projects/inkstone-armv7.apk ~/Dropbox/Projects/inkstone-armv7.bak.apk
mv ~/Dropbox/Projects/inkstone-x86.apk ~/Dropbox/Projects/inkstone-x86.bak.apk
mv ~/Dropbox/Projects/inkstone-armv7.new.apk ~/Dropbox/Projects/inkstone-armv7.apk
mv ~/Dropbox/Projects/inkstone-x86.new.apk ~/Dropbox/Projects/inkstone-x86.apk
